name: node

on: push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Start postgres
        run: docker compose up -d --renew-anon-volumes
      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: yarn
      - name: install
        run: yarn install --frozen-lockfile
      - name: lockfile policy
        run: yarn check:lockfile
      - name: build
        run: yarn build
      - name: linter
        run: yarn lint
        if: ${{ always() }}
      - name: test
        run: yarn test -- --passWithNoTests
      - name: integration test
        run: yarn test:integration -- --passWithNoTests
      # - name: Report coverage
      #   uses: coverallsapp/github-action@master
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop postgres
        if: always()
        run: docker compose down -v
