name: node

on: push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Start postgres
        run: docker compose up -d --renew-anon-volumes
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: linter
        run: npm run lint
        if: ${{ always() }}
      - name: test
        run: npm run test
      - name: integration test
        run: npm run test:integration
      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Stop postgres
        if: always()
        run: docker compose down -v
